name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: ['1.23', '1.24']    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
  
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.goVer }}

    - name: Test with Coverage
      run: go test -coverpkg=./... -v -short -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.txt
